from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CalibrationEntry:
    target_gene: str
    modality: str
    delivery: str
    disease: str
    outcome: str
    notes: str = ""


CALIBRATION_SET = [
    CalibrationEntry(
        "VEGF",
        "mAb",
        "systemic",
        "cancer",
        "SUCCESS",
        "Bevacizumab — anti-angiogenic therapy with broad clinical use.",
    ),
    CalibrationEntry(
        "VEGF",
        "mAb",
        "systemic",
        "heart failure",
        "FAIL",
        "Same pathway but poor disease-context fit for heart failure.",
    ),
    CalibrationEntry(
        "CXCR4",
        "small molecule",
        "systemic",
        "stem cell mobilization",
        "SUCCESS",
        "Plerixafor (AMD3100) is a validated CXCR4-directed success.",
    ),
    CalibrationEntry(
        "NGF",
        "mAb",
        "systemic",
        "osteoarthritis pain",
        "FAIL",
        "Tanezumab showed chronic systemic safety liabilities including RPOA.",
    ),
    CalibrationEntry(
        "CGRP",
        "mAb",
        "systemic",
        "migraine",
        "SUCCESS",
        "Erenumab reflects high specificity with a strong clinical profile.",
    ),
    CalibrationEntry(
        "TNF",
        "mAb",
        "systemic",
        "rheumatoid arthritis",
        "SUCCESS",
        "Adalimumab is a canonical central-pathway autoimmune success.",
    ),
    CalibrationEntry(
        "PCSK9",
        "mAb",
        "systemic",
        "hyperlipidemia",
        "SUCCESS",
        "Evolocumab benefits from secreted-target accessibility and strong efficacy.",
    ),
    CalibrationEntry(
        "CCR5",
        "small molecule",
        "oral",
        "HIV",
        "SUCCESS",
        "Maraviroc shows a feasible receptor-targeting small-molecule path.",
    ),
    CalibrationEntry(
        "APP",
        "mAb",
        "systemic",
        "alzheimer",
        "FAIL",
        "Amyloid-targeting benefit remained weak despite heavy investment.",
    ),
    CalibrationEntry(
        "CXCL12",
        "aptamer",
        "systemic",
        "CLL",
        "SUCCESS",
        "Olaptesired (NOX-A12) Phase 2 showed meaningful response in CLL, validating CXCL12 axis.",
    ),
    CalibrationEntry(
        "NGF",
        "mAb",
        "systemic",
        "chronic low back pain",
        "FAIL",
        "Tanezumab Phase 3 RPOA class effect confirmed across pain indications; FDA CRL 2021.",
    ),
    CalibrationEntry(
        "CXCL12",
        "VHH nanobody",
        "mRNA-LNP local",
        "scar tissue hyperinnervation",
        "SUCCESS",
        "Preclinical validated: GEO 3 datasets (log2FC 1.80), AMD3100 pain model positive, cross-indication consistent. neuroregen composite 0.634.",
    ),
    # ── Oncology SUCCESS ─────────────────────────────────────────────
    CalibrationEntry(
        "HER2",
        "mAb",
        "systemic",
        "breast cancer",
        "SUCCESS",
        "Trastuzumab (Herceptin) — HER2-positive breast cancer standard of care.",
    ),
    CalibrationEntry(
        "PD1",
        "mAb",
        "systemic",
        "melanoma",
        "SUCCESS",
        "Pembrolizumab (Keytruda) — anti-PD-1 checkpoint inhibitor, durable responses in melanoma.",
    ),
    CalibrationEntry(
        "PDL1",
        "mAb",
        "systemic",
        "lung cancer",
        "SUCCESS",
        "Atezolizumab (Tecentriq) — PD-L1 inhibitor approved for NSCLC and other solid tumors.",
    ),
    CalibrationEntry(
        "BRAF",
        "small molecule",
        "oral",
        "melanoma",
        "SUCCESS",
        "Vemurafenib — BRAF V600E inhibitor with high response rate in BRAF-mutant melanoma.",
    ),
    CalibrationEntry(
        "BCR-ABL",
        "small molecule",
        "oral",
        "CML",
        "SUCCESS",
        "Imatinib (Gleevec) — paradigm-shifting TKI, transformed CML from fatal to manageable.",
    ),
    CalibrationEntry(
        "EGFR",
        "small molecule",
        "oral",
        "NSCLC",
        "SUCCESS",
        "Erlotinib — EGFR TKI approved for EGFR-mutant non-small cell lung cancer.",
    ),
    CalibrationEntry(
        "CD20",
        "mAb",
        "systemic",
        "lymphoma",
        "SUCCESS",
        "Rituximab — first mAb approved for cancer, transformed B-cell lymphoma treatment.",
    ),
    # ── Autoimmune / Inflammation SUCCESS ────────────────────────────
    CalibrationEntry(
        "IL17A",
        "mAb",
        "systemic",
        "psoriasis",
        "SUCCESS",
        "Secukinumab — anti-IL-17A mAb with superior PASI responses in moderate-to-severe psoriasis.",
    ),
    CalibrationEntry(
        "IL23",
        "mAb",
        "systemic",
        "psoriasis",
        "SUCCESS",
        "Guselkumab — selective IL-23p19 inhibitor with high durability in psoriasis.",
    ),
    CalibrationEntry(
        "JAK1",
        "small molecule",
        "oral",
        "rheumatoid arthritis",
        "SUCCESS",
        "Tofacitinib — first oral JAK inhibitor approved for RA, UC, and psoriatic arthritis.",
    ),
    CalibrationEntry(
        "IL4R",
        "mAb",
        "systemic",
        "atopic dermatitis",
        "SUCCESS",
        "Dupilumab — IL-4R alpha blocker, first biologic for moderate-to-severe atopic dermatitis.",
    ),
    CalibrationEntry(
        "CD80/86",
        "fusion protein",
        "systemic",
        "rheumatoid arthritis",
        "SUCCESS",
        "Abatacept (CTLA4-Ig) — selective co-stimulation modulator for RA.",
    ),
    CalibrationEntry(
        "RANKL",
        "mAb",
        "systemic",
        "osteoporosis",
        "SUCCESS",
        "Denosumab — RANKL inhibitor reducing fracture risk in postmenopausal osteoporosis.",
    ),
    # ── Cardiovascular / Metabolic SUCCESS ───────────────────────────
    CalibrationEntry(
        "GLP1R",
        "peptide",
        "subcutaneous",
        "type 2 diabetes",
        "SUCCESS",
        "Semaglutide — GLP-1 receptor agonist with cardiovascular and weight benefits.",
    ),
    CalibrationEntry(
        "SGLT2",
        "small molecule",
        "oral",
        "type 2 diabetes",
        "SUCCESS",
        "Empagliflozin — SGLT2 inhibitor with proven cardiovascular and renal outcomes.",
    ),
    CalibrationEntry(
        "Factor Xa",
        "small molecule",
        "oral",
        "atrial fibrillation",
        "SUCCESS",
        "Rivaroxaban — direct oral anticoagulant replacing warfarin for stroke prevention.",
    ),
    # ── Rare Disease SUCCESS ─────────────────────────────────────────
    CalibrationEntry(
        "SMN2",
        "antisense",
        "intrathecal",
        "SMA",
        "SUCCESS",
        "Nusinersen (Spinraza) — antisense oligonucleotide modifying SMN2 splicing in spinal muscular atrophy.",
    ),
    CalibrationEntry(
        "CFTR",
        "small molecule",
        "oral",
        "cystic fibrosis",
        "SUCCESS",
        "Ivacaftor — CFTR potentiator restoring chloride channel function in CF patients with gating mutations.",
    ),
    CalibrationEntry(
        "C5",
        "mAb",
        "systemic",
        "PNH",
        "SUCCESS",
        "Eculizumab — complement C5 inhibitor, transformative therapy for paroxysmal nocturnal hemoglobinuria.",
    ),
    # ── Neuroscience SUCCESS ─────────────────────────────────────────
    CalibrationEntry(
        "CGRP",
        "mAb",
        "systemic",
        "cluster headache",
        "SUCCESS",
        "Galcanezumab — anti-CGRP mAb approved for episodic cluster headache prevention.",
    ),
    # ── Oncology FAIL ────────────────────────────────────────────────
    CalibrationEntry(
        "IDO1",
        "small molecule",
        "oral",
        "melanoma",
        "FAIL",
        "Epacadostat — IDO1 inhibitor failed Phase 3 ECHO-301 in combination with pembrolizumab.",
    ),
    CalibrationEntry(
        "PI3K",
        "small molecule",
        "oral",
        "solid tumors",
        "FAIL",
        "Multiple PI3K inhibitors (pictilisib, buparlisib) failed in solid tumors due to toxicity and limited efficacy.",
    ),
    CalibrationEntry(
        "MET",
        "mAb",
        "systemic",
        "gastric cancer",
        "FAIL",
        "Onartuzumab — anti-MET mAb failed Phase 3 METGastric trial, no OS benefit.",
    ),
    # ── Neuroscience FAIL ────────────────────────────────────────────
    CalibrationEntry(
        "BACE1",
        "small molecule",
        "oral",
        "alzheimer",
        "FAIL",
        "Verubecestat, atabecestat — BACE1 inhibitors worsened cognition in Phase 2/3 Alzheimer trials.",
    ),
    CalibrationEntry(
        "5HT2A",
        "small molecule",
        "oral",
        "schizophrenia negative symptoms",
        "FAIL",
        "Pimavanserin — 5-HT2A inverse agonist showed mixed results for schizophrenia negative symptoms.",
    ),
    CalibrationEntry(
        "TAU",
        "mAb",
        "systemic",
        "alzheimer",
        "FAIL",
        "Semorinemab — anti-tau mAb failed Phase 2 LAURIET trial, no cognitive benefit.",
    ),
    CalibrationEntry(
        "GluN2B",
        "small molecule",
        "oral",
        "depression",
        "FAIL",
        "Multiple GluN2B-selective NMDA antagonists (traxoprodil, radiprodil) failed in depression trials.",
    ),
    # ── Cardiovascular FAIL ──────────────────────────────────────────
    CalibrationEntry(
        "CETP",
        "small molecule",
        "oral",
        "cardiovascular disease",
        "FAIL",
        "Torcetrapib — CETP inhibitor raised HDL but caused excess deaths (ILLUMINATE trial terminated).",
    ),
    CalibrationEntry(
        "PPAR-gamma",
        "small molecule",
        "oral",
        "type 2 diabetes",
        "FAIL",
        "Rosiglitazone — PPAR-gamma agonist linked to increased cardiovascular risk, heavily restricted.",
    ),
    # ── Other FAIL ───────────────────────────────────────────────────
    CalibrationEntry(
        "CCR2",
        "small molecule",
        "oral",
        "diabetic nephropathy",
        "FAIL",
        "Multiple CCR2 antagonists (CCX140-B, others) failed to show clinical benefit in diabetic nephropathy.",
    ),
    CalibrationEntry(
        "LOXL2",
        "mAb",
        "systemic",
        "liver fibrosis",
        "FAIL",
        "Simtuzumab — anti-LOXL2 mAb failed Phase 2 in hepatic fibrosis (PSC, NASH).",
    ),
    CalibrationEntry(
        "Myostatin",
        "mAb",
        "systemic",
        "muscular dystrophy",
        "FAIL",
        "Stamulumab (MYO-029) — anti-myostatin mAb showed no significant efficacy in muscular dystrophies.",
    ),
    # ── Additional SUCCESS entries ───────────────────────────────────
    CalibrationEntry(
        "IL6R",
        "mAb",
        "systemic",
        "rheumatoid arthritis",
        "SUCCESS",
        "Tocilizumab — IL-6 receptor blocker approved for RA, also used in cytokine storm.",
    ),
    CalibrationEntry(
        "BTK",
        "small molecule",
        "oral",
        "CLL",
        "SUCCESS",
        "Ibrutinib — first-in-class BTK inhibitor that transformed CLL and mantle cell lymphoma treatment.",
    ),
    CalibrationEntry(
        "ALK",
        "small molecule",
        "oral",
        "NSCLC ALK-positive",
        "SUCCESS",
        "Crizotinib — ALK inhibitor with high response rate in ALK-rearranged NSCLC.",
    ),
    CalibrationEntry(
        "IL5",
        "mAb",
        "systemic",
        "severe eosinophilic asthma",
        "SUCCESS",
        "Mepolizumab — anti-IL-5 mAb reducing exacerbations in severe eosinophilic asthma.",
    ),
    CalibrationEntry(
        "IgE",
        "mAb",
        "systemic",
        "allergic asthma",
        "SUCCESS",
        "Omalizumab — anti-IgE mAb reducing exacerbations in moderate-to-severe allergic asthma.",
    ),
    CalibrationEntry(
        "CTLA4",
        "mAb",
        "systemic",
        "melanoma",
        "SUCCESS",
        "Ipilimumab — first checkpoint inhibitor approved, demonstrated OS benefit in metastatic melanoma.",
    ),
    CalibrationEntry(
        "CD19",
        "CAR-T",
        "systemic",
        "ALL",
        "SUCCESS",
        "Tisagenlecleucel — anti-CD19 CAR-T cell therapy with high remission rates in relapsed/refractory ALL.",
    ),
    CalibrationEntry(
        "DPP4",
        "small molecule",
        "oral",
        "type 2 diabetes",
        "SUCCESS",
        "Sitagliptin — DPP-4 inhibitor with established glucose-lowering efficacy and safety.",
    ),
    # ── Additional FAIL entries ──────────────────────────────────────
    CalibrationEntry(
        "Endothelin-A",
        "small molecule",
        "oral",
        "heart failure",
        "FAIL",
        "Darusentan — endothelin receptor antagonist failed Phase 3 in resistant hypertension/heart failure.",
    ),
    CalibrationEntry(
        "p53",
        "small molecule",
        "oral",
        "solid tumors",
        "FAIL",
        "Idasanutlin (MDM2-p53) — reactivating p53 showed insufficient clinical benefit in solid tumor Phase 2/3.",
    ),
    CalibrationEntry(
        "PCSK9",
        "siRNA",
        "systemic",
        "heart failure",
        "FAIL",
        "PCSK9 lowering did not improve heart failure outcomes despite lipid reduction (context mismatch).",
    ),
]
